version: '3'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./run/mongodb:/data/db
    networks:
      - mongo-cluster
    restart: unless-stopped
    command: mongod --replSet rs0 --bind_ip localhost,mongo1

networks:
  mongo-cluster:
    